name: Criar Instalador Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java (necessário para o Flutter Android, mas bom ter no ambiente)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.16.0' # Podes ajustar para a versão que usas ou deixar 'any'
        
    - name: Instalar Dependências
      run: flutter pub get

    - name: Construir Executável (Release)
      run: flutter build windows --release

    - name: Compilar Instalador (Inno Setup)
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: setup.iss
    


    - name: Upload do Instalador gerado
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-PinheiroSociety
        path: Output/InstaladorWindows.exe
